apiVersion: v1
kind: Service
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: todo-api
  type: LoadBalancer
