apiVersion: v1
kind: Service
metadata:
  name: todo-db
spec:
  ports:
    - name: todo-db
      port: 2433
      protocol: TCP
      targetPort: 2433
  selector:
    name: todo-db
  type: LoadBalancer
