apiVersion: v1
kind: Service
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  ports:
    - port: 2433
      protocol: TCP
      targetPort: 2433
  selector:
    app: todo-db
  type: LoadBalancer
